name: flutter_codemirror
description: .
homepage: https://github.com/CurrentIndex/flutter_codemirror.git
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^3.0.4
  local_assets_server: ^2.0.2+12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - codemirror/
    - codemirror/assets/
